/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GroceryCounterTest {

  @Test
  void testInitialValue() {
    GroceryCounter c = new GroceryCounter();
    assertEquals("$0.00", c.total());
    assertEquals(0, c.overflows());
  }

  @Test
  void testBasicIncrements() {
    GroceryCounter c = new GroceryCounter();
    c.tens();
    c.tens();
    c.hundreths();
    assertEquals("$20.01", c.total());
    assertEquals(0, c.overflows());
  }

  @Test
  void testOnesLoopNoOverflow() {
    GroceryCounter c = new GroceryCounter();
    for (int i = 0; i < 35; i++) {
      c.ones();
    }
    assertEquals("$35.00", c.total());
    assertEquals(0, c.overflows());
  }

  @Test 
  void testOverflow() {
    GroceryCounter c = new GroceryCounter();
    for (int i = 0; i < 100; i++) {
      c.ones();
    }
    assertEquals("$0.00", c.total());
    assertEquals(1, c.overflows());
  }

  @Test 
  void testClear() {
    GroceryCounter c = new GroceryCounter();
    c.tens();
    c.hundreths();
    c.clear();
    assertEquals("$0.00", c.total());
    assertEquals(0, c.overflows());
  }
}
